### PR TITLE
Cucumber features

### PR DESCRIPTION
**Pull request by demonh3x**
@jsuchy, @felipesere, @christophgockel 

It uses Java 8, AssertJ and Cucumber.

The Cucumber version uses the annotated step definitions instead of the lambda version because it has issues with certain JDK versions.

### CODE REVIEW

**Comment by demonh3x** [comment]
Do we want to change `$` to `£`?

**Comment by jsuchy** [comment]
:+1: $ => £

**Comment by gemcfadyen** [comment]
:+1:

**Comment by felipesere** [comment]
Two quick changes in the `pom.xml` file allow us to go back Java7.

I will merge this and open a Java7 branch just in case...

**Pull request merged**
